---

- hosts: all
  vars_files:
      - config/secrets.yml
      - config/vars.yml

  pre_tasks:
      - name: Install required packages
        apt:
          name: python3
          state: present
          update_cache: yes

      - name: Add ondrej repository for mysql-5.5
        apt_repository: repo='ppa:ondrej/mysql-5.5' update_cache=yes

      - name: Put ssh key on server for passwordless login

  roles:
      - role: geerlingguy.mysql
        become: yes
        mysql_packages:
            - mysql-5.5

  tasks:
      - name: Copy the database setup script to the remote host
        template:
            src: templates/{{ totem_db_structure_file }}
            dest: /totems/{{ totem_db_structure_file }}

      - name: Set up totem database
        mysql_db:
            state: import
            name: all
            target: /totems/{{ totem_db_structure_file }}
