---
totem_db_name: totem
totem_db_structure_file: totem_db_structure.sql

# config for ansible role geerlingguy.mysql
mysql_root_password: "{{ root_password }}"
mysql_databases:
    - name: "{{ totem_db_name }}"
      encoding: latin1
      collation: latin1_general_ci
mysql_users:
    - name: player
      host: "%"
      password: "{{ player_password }}"
      priv: "totem.*:ALL"
