---

# config for ansible role geerlingguy.mysql
mysql_root_password: {{ root_password }}
mysql_databases:
    - name: totem
      encoding: latin1
      collation: latin1_general_ci
mysql_users:
    - name: player
      host: "%"
      password: {{ player_password }}
      priv: "totem.*:ALL"
